// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwora8dAaWmPh3zwzVVSLWT3fc5f3tzzg',
    appId: '1:679097350594:web:311267c0bac4b55ca7fe5b',
    messagingSenderId: '679097350594',
    projectId: 'smc241024',
    authDomain: 'smc241024.firebaseapp.com',
    storageBucket: 'smc241024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDed08PkjyfeC66lsi6QsbiQlvJKeS-PXk',
    appId: '1:679097350594:android:54383f7eaf093f2aa7fe5b',
    messagingSenderId: '679097350594',
    projectId: 'smc241024',
    storageBucket: 'smc241024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg66YoaHOYH-QnmuJHSCVh4gOCI3GplMQ',
    appId: '1:679097350594:ios:7bb414b736ac11a0a7fe5b',
    messagingSenderId: '679097350594',
    projectId: 'smc241024',
    storageBucket: 'smc241024.appspot.com',
    iosBundleId: 'com.example.smc241024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg66YoaHOYH-QnmuJHSCVh4gOCI3GplMQ',
    appId: '1:679097350594:ios:7bb414b736ac11a0a7fe5b',
    messagingSenderId: '679097350594',
    projectId: 'smc241024',
    storageBucket: 'smc241024.appspot.com',
    iosBundleId: 'com.example.smc241024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwora8dAaWmPh3zwzVVSLWT3fc5f3tzzg',
    appId: '1:679097350594:web:5904d590737121c9a7fe5b',
    messagingSenderId: '679097350594',
    projectId: 'smc241024',
    authDomain: 'smc241024.firebaseapp.com',
    storageBucket: 'smc241024.appspot.com',
  );
}
